// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quanlinhahang.Data;

#nullable disable

namespace Quanlinhahang.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251113163201_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quanlinhahang.Models.BanPhong", b =>
                {
                    b.Property<int>("BanPhongID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BanPhongID"));

                    b.Property<int>("LoaiBanPhongID")
                        .HasColumnType("int");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenBanPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BanPhongID");

                    b.ToTable("BanPhong");
                });

            modelBuilder.Entity("Quanlinhahang.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("HoaDonID")
                        .HasColumnType("int");

                    b.Property<int>("MonAnID")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HoaDonID", "MonAnID");

                    b.HasIndex("MonAnID");

                    b.ToTable("ChiTietHoaDon");
                });

            modelBuilder.Entity("Quanlinhahang.Models.DatBan", b =>
                {
                    b.Property<int>("DatBanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DatBanID"));

                    b.Property<int?>("BanPhongID")
                        .HasColumnType("int");

                    b.Property<int?>("BanPhongID1")
                        .HasColumnType("int");

                    b.Property<int>("KhachHangID")
                        .HasColumnType("int");

                    b.Property<int>("KhungGioID")
                        .HasColumnType("int");

                    b.Property<int?>("KhungGioID1")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoNguoi")
                        .HasColumnType("int");

                    b.Property<decimal?>("TongTienDuKien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YeuCauDacBiet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DatBanID");

                    b.HasIndex("BanPhongID");

                    b.HasIndex("BanPhongID1");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("KhungGioID");

                    b.HasIndex("KhungGioID1");

                    b.ToTable("DatBan");
                });

            modelBuilder.Entity("Quanlinhahang.Models.HoaDon", b =>
                {
                    b.Property<int>("HoaDonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoaDonID"));

                    b.Property<int>("DatBanID")
                        .HasColumnType("int");

                    b.Property<int?>("DatBanID1")
                        .HasColumnType("int");

                    b.Property<int>("DiemCong")
                        .HasColumnType("int");

                    b.Property<int>("DiemSuDung")
                        .HasColumnType("int");

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhThucThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TaiKhoanID")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HoaDonID");

                    b.HasIndex("DatBanID");

                    b.HasIndex("DatBanID1");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("Quanlinhahang.Models.KhachHang", b =>
                {
                    b.Property<int>("KhachHangID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhachHangID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HangThanhVienID")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KhachHangID");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("Quanlinhahang.Models.KhungGio", b =>
                {
                    b.Property<int>("KhungGioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhungGioID"));

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<string>("TenKhungGio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KhungGioID");

                    b.ToTable("KhungGio");
                });

            modelBuilder.Entity("Quanlinhahang.Models.MonAn", b =>
                {
                    b.Property<int>("MonAnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonAnID"));

                    b.Property<int>("DanhMucID")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnhURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiMon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MonAnID");

                    b.ToTable("MonAn");
                });

            modelBuilder.Entity("Quanlinhahang.Models.TaiKhoan", b =>
                {
                    b.Property<int>("TaiKhoanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaiKhoanID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaiKhoanID");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("Quanlinhahang.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("Quanlinhahang.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTiet")
                        .HasForeignKey("HoaDonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quanlinhahang.Models.MonAn", "MonAn")
                        .WithMany()
                        .HasForeignKey("MonAnID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("Quanlinhahang.Models.DatBan", b =>
                {
                    b.HasOne("Quanlinhahang.Models.BanPhong", "BanPhong")
                        .WithMany()
                        .HasForeignKey("BanPhongID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Quanlinhahang.Models.BanPhong", null)
                        .WithMany("DatBans")
                        .HasForeignKey("BanPhongID1");

                    b.HasOne("Quanlinhahang.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Quanlinhahang.Models.KhungGio", "KhungGio")
                        .WithMany()
                        .HasForeignKey("KhungGioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Quanlinhahang.Models.KhungGio", null)
                        .WithMany("DatBans")
                        .HasForeignKey("KhungGioID1");

                    b.Navigation("BanPhong");

                    b.Navigation("KhachHang");

                    b.Navigation("KhungGio");
                });

            modelBuilder.Entity("Quanlinhahang.Models.HoaDon", b =>
                {
                    b.HasOne("Quanlinhahang.Models.DatBan", "DatBan")
                        .WithMany()
                        .HasForeignKey("DatBanID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Quanlinhahang.Models.DatBan", null)
                        .WithMany("HoaDons")
                        .HasForeignKey("DatBanID1");

                    b.Navigation("DatBan");
                });

            modelBuilder.Entity("Quanlinhahang.Models.BanPhong", b =>
                {
                    b.Navigation("DatBans");
                });

            modelBuilder.Entity("Quanlinhahang.Models.DatBan", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Quanlinhahang.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTiet");
                });

            modelBuilder.Entity("Quanlinhahang.Models.KhungGio", b =>
                {
                    b.Navigation("DatBans");
                });
#pragma warning restore 612, 618
        }
    }
}
